In [2]:
import numpy as np

In [24]:
a = np.arange(100)
a = a.reshape(10,10)

In [26]:
a[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
a[0:len(a),0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
a[...,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
all(a[...,2] == a[0:len(a),2])

True

In [23]:
a[[1,2,3],[5,6,9]]

array([15, 26, 39])